name: (Test) Build lsfg-vk
on:
  push:
    branches: ["test/deploying"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install build dependencies
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: git
          clang llvm
          cmake ninja-build
          libvulkan-dev
        version: 1.0
        execute_install_scripts: true
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Configure with CMake and Ninja
      run: |
        cmake -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=./build-release
    - name: Build with Ninja
      run: |
        ninja -C build
    - name: Install with CMake
      run: |
        cmake --install build --strip
    - name: Upload lsfg-vk artifact
      uses: actions/upload-artifact@v4
      with:
        name: lsfg-vk_TEST
        path: |
          build-release/share/vulkan/implicit_layer.d/VkLayer_LS_frame_generation.json
          build-release/lib/liblsfg-vk.so
